// Code generated by "stringer -type SettingsType"; DO NOT EDIT.

package settings

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderTableSize-1]
	_ = x[EnablePush-2]
	_ = x[MaxConcurrentStreams-3]
	_ = x[InitialWindowSize-4]
	_ = x[MaxFrameSize-5]
	_ = x[MaxHeaderListSize-6]
}

const _SettingsType_name = "HeaderTableSizeEnablePushMaxConcurrentStreamsInitialWindowSizeMaxFrameSizeMaxHeaderListSize"

var _SettingsType_index = [...]uint8{0, 15, 25, 45, 62, 74, 91}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_SettingsType_index)-1) {
		return "SettingsType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SettingsType_name[_SettingsType_index[i]:_SettingsType_index[i+1]]
}
