// Code generated by "stringer -type=LiteralIndexType"; DO NOT EDIT.

package hpack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IncrementalIndex-0]
	_ = x[NoIndex-1]
	_ = x[NeverIndex-2]
}

const _LiteralIndexType_name = "IncrementalIndexNoIndexNeverIndex"

var _LiteralIndexType_index = [...]uint8{0, 16, 23, 33}

func (i LiteralIndexType) String() string {
	if i >= LiteralIndexType(len(_LiteralIndexType_index)-1) {
		return "LiteralIndexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LiteralIndexType_name[_LiteralIndexType_index[i]:_LiteralIndexType_index[i+1]]
}
