// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorCodeNoError-0]
	_ = x[ErrorCodeProtocol-1]
	_ = x[ErrorCodeInternal-2]
	_ = x[ErrorCodeFlowControl-3]
	_ = x[ErrorCodeSettingsTimeout-4]
	_ = x[ErrorCodeStreamClosed-5]
	_ = x[ErrorCodeFrameSize-6]
	_ = x[ErrorCodeRefusedStream-7]
	_ = x[ErrorCodeCancel-8]
	_ = x[ErrorCodeCompression-9]
	_ = x[ErrorCodeConnect-10]
	_ = x[ErrorCodeEnhanceYourCalm-11]
	_ = x[ErrorCodeHttp11Required-12]
}

const _ErrorCode_name = "ErrorCodeNoErrorErrorCodeProtocolErrorCodeInternalErrorCodeFlowControlErrorCodeSettingsTimeoutErrorCodeStreamClosedErrorCodeFrameSizeErrorCodeRefusedStreamErrorCodeCancelErrorCodeCompressionErrorCodeConnectErrorCodeEnhanceYourCalmErrorCodeHttp11Required"

var _ErrorCode_index = [...]uint8{0, 16, 33, 50, 70, 94, 115, 133, 155, 170, 190, 206, 230, 253}

func (i ErrorCode) String() string {
	if i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
