// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorCodeUnset - -1]
	_ = x[ErrorCodeNoError-0]
	_ = x[ErrorCodeProtocol-1]
	_ = x[ErrorCodeInternal-2]
	_ = x[ErrorCodeFlowControl-3]
	_ = x[ErrorCodeSettingsTimeout-4]
	_ = x[ErrorCodeStreamClosed-5]
	_ = x[ErrorCodeFrameSize-6]
	_ = x[ErrorCodeRefusedStream-7]
	_ = x[ErrorCodeCancel-8]
	_ = x[ErrorCodeCompression-9]
	_ = x[ErrorCodeConnect-10]
	_ = x[ErrorCodeEnhanceYourCalm-11]
	_ = x[ErrorCodeHttp11Required-12]
}

const _ErrorCode_name = "ErrorCodeUnsetErrorCodeNoErrorErrorCodeProtocolErrorCodeInternalErrorCodeFlowControlErrorCodeSettingsTimeoutErrorCodeStreamClosedErrorCodeFrameSizeErrorCodeRefusedStreamErrorCodeCancelErrorCodeCompressionErrorCodeConnectErrorCodeEnhanceYourCalmErrorCodeHttp11Required"

var _ErrorCode_index = [...]uint16{0, 14, 30, 47, 64, 84, 108, 129, 147, 169, 184, 204, 220, 244, 267}

func (i ErrorCode) String() string {
	i -= -1
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
