// Code generated by "stringer -type SettingsType"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SettingsHeaderTableSize-1]
	_ = x[SettingsEnablePush-2]
	_ = x[SettingsMaxConcurrentStreams-3]
	_ = x[SettingsInitialWindowSize-4]
	_ = x[SettingsMaxFrameSize-5]
	_ = x[SettingsMaxHeaderListSize-6]
}

const _SettingsType_name = "SettingsHeaderTableSizeSettingsEnablePushSettingsMaxConcurrentStreamsSettingsInitialWindowSizeSettingsMaxFrameSizeSettingsMaxHeaderListSize"

var _SettingsType_index = [...]uint8{0, 23, 41, 69, 94, 114, 139}

func (i SettingsType) String() string {
	i -= 1
	if i >= SettingsType(len(_SettingsType_index)-1) {
		return "SettingsType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SettingsType_name[_SettingsType_index[i]:_SettingsType_index[i+1]]
}
