// Code generated by "stringer -type=StreamError"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StreamErrorNoError-0]
	_ = x[StreamErrorProtocol-1]
	_ = x[StreamErrorInternal-2]
	_ = x[StreamErrorFlowControl-3]
	_ = x[StreamErrorSettingsTimeout-4]
	_ = x[StreamErrorStreamClosed-5]
	_ = x[StreamErrorFrameSize-6]
	_ = x[StreamErrorRefusedStream-7]
	_ = x[StreamErrorCancel-8]
	_ = x[StreamErrorCompression-9]
	_ = x[StreamErrorConnect-10]
	_ = x[StreamErrorEnhanceYourCalm-11]
	_ = x[StreamErrorHttp11Required-12]
}

const _StreamError_name = "StreamErrorNoErrorStreamErrorProtocolStreamErrorInternalStreamErrorFlowControlStreamErrorSettingsTimeoutStreamErrorStreamClosedStreamErrorFrameSizeStreamErrorRefusedStreamStreamErrorCancelStreamErrorCompressionStreamErrorConnectStreamErrorEnhanceYourCalmStreamErrorHttp11Required"

var _StreamError_index = [...]uint16{0, 18, 37, 56, 78, 104, 127, 147, 171, 188, 210, 228, 254, 279}

func (i StreamError) String() string {
	if i >= StreamError(len(_StreamError_index)-1) {
		return "StreamError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StreamError_name[_StreamError_index[i]:_StreamError_index[i+1]]
}
