// Code generated by "stringer -type=StreamState"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StreamStateUnset-0]
	_ = x[StreamStateIdle-1]
	_ = x[StreamStateLocalReserved-2]
	_ = x[StreamStateRemoteReserved-3]
	_ = x[StreamStateOpen-4]
	_ = x[StreamStateRemoteClosed-5]
	_ = x[StreamStateLocalClosed-6]
	_ = x[StreamStateClosed-7]
}

const _StreamState_name = "StreamStateUnsetStreamStateIdleStreamStateLocalReservedStreamStateRemoteReservedStreamStateOpenStreamStateRemoteClosedStreamStateLocalClosedStreamStateClosed"

var _StreamState_index = [...]uint8{0, 16, 31, 55, 80, 95, 118, 140, 157}

func (i StreamState) String() string {
	if i >= StreamState(len(_StreamState_index)-1) {
		return "StreamState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StreamState_name[_StreamState_index[i]:_StreamState_index[i+1]]
}
